package it.szyszka.skillmarket.modules.user.api;

/**
 * Created by rafal on 04.10.17.
 */

public enum UserResponse {

    NO_RESPONSE,
    USER_SAVED, EMAIL_TAKEN, NICKNAME_TAKEN,
    FAILED_TO_CREATE_TRUST_RELATION, SUCCESSFULLY_CREATED_TRUST_RELATION, FAILED_TO_CREATE_FRIEND_RELATION, SUCCESSFULLY_CREATED_FRIEND_RELATION,
    USER_ACCOUNT_ACTIVATED, TOKEN_NOT_FOUND

}
